/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stations/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Catalog */
        get: operations["search_catalog_v1_stations_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stations */
        get: operations["list_stations_v1_stations_get"];
        put?: never;
        /** Create Station */
        post: operations["create_station_v1_stations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stations/{station_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Station */
        delete: operations["delete_station_v1_stations__station_id__delete"];
        options?: never;
        head?: never;
        /** Update Station */
        patch: operations["update_station_v1_stations__station_id__patch"];
        trace?: never;
    };
    "/v1/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Home */
        get: operations["get_home_v1_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trends */
        get: operations["get_trends_v1_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stations/{station_id}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Station Detail */
        get: operations["get_station_detail_v1_stations__station_id__detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/map/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Map Overview */
        get: operations["get_map_overview_v1_map_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Alert */
        get: operations["current_alert_v1_alerts_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/{station_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_v1_reports__station_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/geo/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_v1_geo_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/geo/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reverse */
        get: operations["reverse_v1_geo_reverse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/map/layers/{layer}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Layer */
        get: operations["get_layer_v1_map_layers__layer__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/satellite/cloud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Satellite Cloud */
        get: operations["satellite_cloud_v1_satellite_cloud_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIReportResponse */
        AIReportResponse: {
            station: components["schemas"]["StationSummary"];
            /** Report Date */
            report_date: string;
            /** Generated At */
            generated_at: string;
            /**
             * Is Fallback
             * @description 供埋点统计，不用于改变展示
             */
            is_fallback: boolean;
            /** Verdict Title */
            verdict_title: string;
            /** Verdict Detail */
            verdict_detail: string;
            /** Periods */
            periods: components["schemas"]["ReportPeriodOut"][];
            /** Risk Title */
            risk_title: string | null;
            /** Risk Detail */
            risk_detail: string | null;
            /** Suggestions */
            suggestions: string[];
            summary: components["schemas"]["ReportSummary"];
        };
        /**
         * AlertLevel
         * @enum {string}
         */
        AlertLevel: "minor" | "moderate" | "severe" | "cleared";
        /** AlertListResponse */
        AlertListResponse: {
            /** Alerts */
            alerts: components["schemas"]["AlertSummary"][];
            /**
             * Next Cursor
             * @description 下一页游标，null 表示没有更多
             */
            next_cursor: string | null;
        };
        /** AlertSummary */
        AlertSummary: {
            /** Id */
            id: string;
            level: components["schemas"]["AlertLevel"];
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Published At */
            published_at: string;
            /** Station Id */
            station_id: string;
            /** Source */
            source: string;
        };
        /** Bounds */
        Bounds: {
            sw: components["schemas"]["LatLng"];
            ne: components["schemas"]["LatLng"];
        };
        /** CatalogPlantOut */
        CatalogPlantOut: {
            /** Id */
            id: string;
            /**
             * Name
             * @description 展示名：有中文名用中文名，否则数据集原名
             */
            name: string;
            /**
             * Name En
             * @description 数据集原名（英文），与 name 相同时为 null
             */
            name_en: string | null;
            type: components["schemas"]["StationType"];
            /**
             * Capacity
             * @description kW
             */
            capacity: number;
            /**
             * Latitude
             * @description 已按 coord 转换
             */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Address
             * @description 省市区，未回填为 null
             */
            address: string | null;
            /** Owner */
            owner: string | null;
            /** Commissioning Year */
            commissioning_year: number | null;
            /**
             * Distance Km
             * @description near 查询时到查询点的距离，其余为 null
             */
            distance_km: number | null;
            /**
             * Source
             * @description wri | gem，展示出处用
             */
            source: string;
        };
        /** CatalogSearchResponse */
        CatalogSearchResponse: {
            /** Plants */
            plants: components["schemas"]["CatalogPlantOut"][];
            /**
             * Total
             * @description 目录内该类型总数，供「共收录 N 座」文案
             */
            total: number;
        };
        /**
         * CloudMotion
         * @description 云团短临外推三宫格。仅卫星短临预警有。docs/07 §四
         */
        CloudMotion: {
            /** Distance Km */
            distance_km: number;
            /** Direction */
            direction: string;
            /** Direction Detail */
            direction_detail: string;
            /** Impact In Minutes */
            impact_in_minutes: number;
            /** Impact Start Time */
            impact_start_time: string;
            /** Reference Station */
            reference_station: string;
        };
        /**
         * Coord
         * @enum {string}
         */
        Coord: "wgs84" | "gcj02";
        /** CreateStationRequest */
        CreateStationRequest: {
            /** Name */
            name: string;
            type: components["schemas"]["StationType"];
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Capacity
             * @description kW
             */
            capacity: number;
            /**
             * @description 入参坐标系
             * @default wgs84
             */
            coord: components["schemas"]["Coord"];
            /** Catalog Id */
            catalog_id?: string | null;
            /** Tilt */
            tilt?: number | null;
            /** Azimuth */
            azimuth?: number | null;
            /** Hub Height */
            hub_height?: number | null;
        };
        /** CurrentAlertResponse */
        CurrentAlertResponse: {
            alert: components["schemas"]["AlertSummary"] | null;
            /** @description 仅卫星短临预警有；预报类为 null */
            cloud_motion: components["schemas"]["CloudMotion"] | null;
            /** @description 上游不可用时为 null */
            satellite: components["schemas"]["SatelliteCloudResponse"] | null;
            /**
             * Satellite Status
             * @description unavailable 表示数据源暂时拿不到；夜间有红外，不再是空态
             * @enum {string}
             */
            satellite_status: "ok" | "unavailable";
        };
        /** CurrentWeather */
        CurrentWeather: {
            /** @description ℃ */
            temperature: components["schemas"]["MetricWithDelta"];
            /**
             * Apparent Temperature
             * @description ℃ 体感
             */
            apparent_temperature: number | null;
            /**
             * Humidity
             * @description %
             */
            humidity: number | null;
            /** @description m/s */
            wind_speed: components["schemas"]["MetricWithDelta"];
            /**
             * Wind Direction
             * @description °
             */
            wind_direction: number | null;
            /** @description % */
            cloud_cover: components["schemas"]["MetricWithDelta"];
            /** @description W/m² */
            radiation: components["schemas"]["MetricWithDelta"];
            /**
             * Weather Text
             * @description 「晴转多云」
             */
            weather_text: string | null;
            /** Observed At */
            observed_at: string;
        };
        /**
         * EnergyIndex
         * @description 环境指数 = 今日预测发电量 / 今日理想发电量 × 100。docs/07 §一
         */
        EnergyIndex: {
            /** Score */
            score?: number | null;
            level?: components["schemas"]["IndexLevel"] | null;
            /**
             * Summary
             * @description AI 一句话结论
             */
            summary?: string | null;
            /**
             * Estimated
             * @description True 表示部分气象因子由气候平均值填补
             * @default false
             */
            estimated: boolean;
            /** Attribution */
            attribution?: components["schemas"]["IndexAttribution"][];
        };
        /** Envelope[AIReportResponse] */
        Envelope_AIReportResponse_: {
            data: components["schemas"]["AIReportResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[AlertListResponse] */
        Envelope_AlertListResponse_: {
            data: components["schemas"]["AlertListResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[CatalogSearchResponse] */
        Envelope_CatalogSearchResponse_: {
            data: components["schemas"]["CatalogSearchResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[CurrentAlertResponse] */
        Envelope_CurrentAlertResponse_: {
            data: components["schemas"]["CurrentAlertResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[GeoReverseResponse] */
        Envelope_GeoReverseResponse_: {
            data: components["schemas"]["GeoReverseResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[GeoSearchResponse] */
        Envelope_GeoSearchResponse_: {
            data: components["schemas"]["GeoSearchResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[HomeResponse] */
        Envelope_HomeResponse_: {
            data: components["schemas"]["HomeResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[LayerResponse] */
        Envelope_LayerResponse_: {
            data: components["schemas"]["LayerResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[LoginResponse] */
        Envelope_LoginResponse_: {
            data: components["schemas"]["LoginResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[MapOverviewResponse] */
        Envelope_MapOverviewResponse_: {
            data: components["schemas"]["MapOverviewResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[SatelliteCloudResponse] */
        Envelope_SatelliteCloudResponse_: {
            data: components["schemas"]["SatelliteCloudResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[StationDetailResponse] */
        Envelope_StationDetailResponse_: {
            data: components["schemas"]["StationDetailResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[StationListResponse] */
        Envelope_StationListResponse_: {
            data: components["schemas"]["StationListResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[StationSummary] */
        Envelope_StationSummary_: {
            data: components["schemas"]["StationSummary"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[TrendSeries] */
        Envelope_TrendSeries_: {
            data: components["schemas"]["TrendSeries"];
            meta: components["schemas"]["Meta"];
        };
        /** GeoPlace */
        GeoPlace: {
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Type
             * @enum {string}
             */
            type: "city" | "poi" | "station" | "coordinate" | "plant";
            /**
             * Catalog Id
             * @description type=plant 时为目录 id，其余 null
             */
            catalog_id: string | null;
        };
        /** GeoReverseResponse */
        GeoReverseResponse: {
            /** Address */
            address: string;
            /** Province */
            province: string;
            /** City */
            city: string;
            /** District */
            district: string;
        };
        /** GeoSearchResponse */
        GeoSearchResponse: {
            /** Results */
            results: components["schemas"]["GeoPlace"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Server Time */
            server_time: string;
        };
        /** HomeResponse */
        HomeResponse: {
            /** Has Station */
            has_station: boolean;
            station: components["schemas"]["StationSummary"] | null;
            index: components["schemas"]["EnergyIndex"] | null;
            weather: components["schemas"]["CurrentWeather"] | null;
            /** @description 24 小时，默认辐射 */
            trends: components["schemas"]["TrendSeries"] | null;
            /** @description 今日最高等级一条，无预警为 null */
            alert: components["schemas"]["AlertSummary"] | null;
        };
        /**
         * IndexAttribution
         * @description 归因：该因子使指数偏离理想值多少分。算出来的，不是权重。docs/07 §1.6
         */
        IndexAttribution: {
            factor: components["schemas"]["IndexAttributionFactor"];
            /**
             * Delta
             * @description 负数为扣分，正数为加分
             */
            delta: number;
            /** Description */
            description: string;
        };
        /**
         * IndexAttributionFactor
         * @enum {string}
         */
        IndexAttributionFactor: "radiation" | "temperature" | "wind";
        /**
         * IndexLevel
         * @enum {string}
         */
        IndexLevel: "excellent" | "good" | "fair" | "poor";
        /** LatLng */
        LatLng: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** LayerFrame */
        LayerFrame: {
            /**
             * Images
             * @description 覆盖请求 bbox 所需的量化块
             */
            images: components["schemas"]["LayerImage"][];
        };
        /** LayerImage */
        LayerImage: {
            /**
             * Url
             * @description 图片地址，带版本号
             */
            url: string;
            /** @description 已按 coord 转换 */
            bounds: components["schemas"]["Bounds"];
        };
        /** LayerResponse */
        LayerResponse: {
            layer: components["schemas"]["LayerType"];
            /**
             * Observed At
             * @description 数据观测时间，非请求时间
             */
            observed_at: string;
            /** Unit */
            unit: string | null;
            legend: components["schemas"]["Legend"];
            /**
             * Frames
             * @description 静态图层长度为 1，风场为多帧
             */
            frames: components["schemas"]["LayerFrame"][];
            /** Frame Interval Ms */
            frame_interval_ms: number | null;
        };
        /**
         * LayerType
         * @enum {string}
         */
        LayerType: "cloud" | "wind" | "temperature" | "radiation";
        /** Legend */
        Legend: {
            /** Title */
            title: string;
            /**
             * Type
             * @description gradient | scale
             */
            type: string;
            /**
             * Stops
             * @description 刻度值；无量纲图层为 null
             */
            stops: number[] | null;
            /**
             * Labels
             * @description 无量纲图层用，如 [低, 高]
             */
            labels: string[] | null;
            /** Colors */
            colors: string[];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Code */
            code: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Token */
            token: string;
            /** Expires In */
            expires_in: number;
        };
        /**
         * MapOverviewResponse
         * @description docs/06 §7.1
         */
        MapOverviewResponse: {
            station: components["schemas"]["StationSummary"];
            index: components["schemas"]["EnergyIndex"] | null;
            weather: components["schemas"]["CurrentWeather"] | null;
            /**
             * Ai Hint
             * @description 底部 AI 提示条一句话
             */
            ai_hint: string | null;
        };
        /** Meta */
        Meta: {
            coord: components["schemas"]["Coord"];
            /** Server Time */
            server_time: string;
        };
        /**
         * MetricWithDelta
         * @description 值 + 环比。delta_percent 为 None 时前端隐藏环比标签。
         */
        MetricWithDelta: {
            /** Value */
            value: number | null;
            /**
             * Delta Percent
             * @description 较昨日同期百分比，None 时前端隐藏标签
             */
            delta_percent: number | null;
        };
        /** ReportPeriodOut */
        ReportPeriodOut: {
            /**
             * Period
             * @enum {string}
             */
            period: "morning" | "afternoon" | "evening";
            /**
             * Weather Summary
             * @description 「晴转多云」
             */
            weather_summary: string;
            /**
             * Generation Impact
             * @description 「发电条件良好」
             */
            generation_impact: string;
            /**
             * Level
             * @description 时间轴节点配色
             * @enum {string}
             */
            level: "good" | "warning" | "risk";
            /**
             * Time Range
             * @description 「06:00 – 12:00」
             */
            time_range: string;
        };
        /** ReportSummary */
        ReportSummary: {
            /** @description kWh */
            generation: components["schemas"]["MetricWithDelta"];
            /** @description h */
            equivalent_hours: components["schemas"]["MetricWithDelta"];
            /** @description kg */
            co2_reduction: components["schemas"]["MetricWithDelta"];
            /** @description 元 */
            estimated_revenue: components["schemas"]["MetricWithDelta"];
        };
        /** SatelliteCloudResponse */
        SatelliteCloudResponse: {
            /**
             * Band
             * @description 服务端按太阳高度角自动选择：白天 visible（真彩展示），夜间 infrared
             * @enum {string}
             */
            band: "visible" | "infrared" | "vapor";
            /**
             * Observed At
             * @description 卫星观测时间，不是请求时间
             */
            observed_at: string;
            image: components["schemas"]["LayerImage"];
            legend: components["schemas"]["Legend"];
            /** @description 已按 coord 转换 */
            station_marker: components["schemas"]["LatLng"];
        };
        /** StationCounts */
        StationCounts: {
            /** All */
            all: number;
            /** Solar */
            solar: number;
            /** Wind */
            wind: number;
        };
        /**
         * StationDetailResponse
         * @description docs/06 §5.3
         */
        StationDetailResponse: {
            station: components["schemas"]["StationSummary"];
            weather: components["schemas"]["CurrentWeather"] | null;
            index: components["schemas"]["EnergyIndex"] | null;
            trends: components["schemas"]["TrendSeries"] | null;
            /**
             * Updated At
             * @description 「数据更新时间」，取气象观测时刻
             */
            updated_at: string;
        };
        /** StationListResponse */
        StationListResponse: {
            /** Stations */
            stations: components["schemas"]["StationSummary"][];
            counts: components["schemas"]["StationCounts"];
        };
        /**
         * StationMetrics
         * @description 运行指标。V1 无实测数据，由气象推算；推算前为 None，前端展示「—」。
         *
         *     字段不带默认值：契约要求缺失一律 null 而非省略（docs/06 §2.5），
         *     带默认值会让 OpenAPI 把字段标成可选，前端类型就会多一层 undefined。
         */
        StationMetrics: {
            /**
             * Daily Generation
             * @description kWh
             */
            daily_generation: number | null;
            /**
             * Current Power
             * @description kW
             */
            current_power: number | null;
            /**
             * Total Generation
             * @description kWh
             */
            total_generation: number | null;
            /**
             * Co2 Reduction
             * @description kg
             */
            co2_reduction: number | null;
        };
        /**
         * StationStatus
         * @enum {string}
         */
        StationStatus: "normal" | "standby" | "fault";
        /** StationSummary */
        StationSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            type: components["schemas"]["StationType"];
            status: components["schemas"]["StationStatus"];
            /**
             * Capacity
             * @description kW，基础单位裸数值，前端负责进位
             */
            capacity: number;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Address */
            address: string | null;
            /** Image */
            image: string | null;
            metrics: components["schemas"]["StationMetrics"];
        };
        /**
         * StationType
         * @enum {string}
         */
        StationType: "solar" | "wind";
        /**
         * TrendMetric
         * @enum {string}
         */
        TrendMetric: "radiation" | "wind_speed" | "cloud_cover";
        /** TrendPoint */
        TrendPoint: {
            /** Time */
            time: string;
            /**
             * Value
             * @description 缺测为 null，前端断线不补 0
             */
            value: number | null;
        };
        /**
         * TrendRange
         * @enum {string}
         */
        TrendRange: "24h" | "7d";
        /** TrendSeries */
        TrendSeries: {
            metric: components["schemas"]["TrendMetric"];
            /** Unit */
            unit: string;
            range: components["schemas"]["TrendRange"];
            /**
             * Y Max
             * @description 固定纵轴上限；null 表示自适应。由服务端下发
             */
            y_max: number | null;
            /** Points */
            points: components["schemas"]["TrendPoint"][];
        };
        /**
         * UpdateStationRequest
         * @description PATCH：全部可选。docs/06 §5.4
         */
        UpdateStationRequest: {
            /** Name */
            name?: string | null;
            type?: components["schemas"]["StationType"] | null;
            status?: components["schemas"]["StationStatus"] | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Capacity */
            capacity?: number | null;
            /** @default wgs84 */
            coord: components["schemas"]["Coord"];
            /** Tilt */
            tilt?: number | null;
            /** Azimuth */
            azimuth?: number | null;
            /** Hub Height */
            hub_height?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_LoginResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_catalog_v1_stations_catalog_get: {
        parameters: {
            query?: {
                keyword?: string | null;
                /** @description latitude,longitude，按 coord */
                near?: string | null;
                /** @description west,south,east,north，按 coord */
                bbox?: string | null;
                type?: components["schemas"]["StationType"] | null;
                limit?: number;
                /** @description 响应中经纬度的坐标系。小程序传 gcj02 */
                coord?: components["schemas"]["Coord"];
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_CatalogSearchResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stations_v1_stations_get: {
        parameters: {
            query?: {
                /** @description 响应中经纬度的坐标系。小程序传 gcj02 */
                coord?: components["schemas"]["Coord"];
                type?: components["schemas"]["StationType"] | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_StationListResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_station_v1_stations_post: {
        parameters: {
            query?: {
                /** @description 响应中经纬度的坐标系。小程序传 gcj02 */
                coord?: components["schemas"]["Coord"];
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_StationSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_station_v1_stations__station_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_station_v1_stations__station_id__patch: {
        parameters: {
            query?: {
                /** @description 响应中经纬度的坐标系。小程序传 gcj02 */
                coord?: components["schemas"]["Coord"];
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_StationSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_home_v1_home_get: {
        parameters: {
            query?: {
                /** @description 响应中经纬度的坐标系。小程序传 gcj02 */
                coord?: components["schemas"]["Coord"];
                station_id?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_HomeResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trends_v1_trends_get: {
        parameters: {
            query: {
                station_id: string;
                metric?: components["schemas"]["TrendMetric"];
                range?: components["schemas"]["TrendRange"];
                /** @description 响应中经纬度的坐标系。小程序传 gcj02 */
                coord?: components["schemas"]["Coord"];
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TrendSeries_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_station_detail_v1_stations__station_id__detail_get: {
        parameters: {
            query?: {
                /** @description 响应中经纬度的坐标系。小程序传 gcj02 */
                coord?: components["schemas"]["Coord"];
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_StationDetailResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_map_overview_v1_map_overview_get: {
        parameters: {
            query?: {
                /** @description 响应中经纬度的坐标系。小程序传 gcj02 */
                coord?: components["schemas"]["Coord"];
                station_id?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MapOverviewResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_v1_alerts_get: {
        parameters: {
            query?: {
                station_id?: string | null;
                level?: string;
                cursor?: string | null;
                limit?: number;
                /** @description 响应中经纬度的坐标系。小程序传 gcj02 */
                coord?: components["schemas"]["Coord"];
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_AlertListResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_alert_v1_alerts_current_get: {
        parameters: {
            query?: {
                station_id?: string | null;
                /** @description 响应中经纬度的坐标系。小程序传 gcj02 */
                coord?: components["schemas"]["Coord"];
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_CurrentAlertResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_v1_reports__station_id__get: {
        parameters: {
            query?: {
                date?: string | null;
                /** @description 响应中经纬度的坐标系。小程序传 gcj02 */
                coord?: components["schemas"]["Coord"];
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_AIReportResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_v1_geo_search_get: {
        parameters: {
            query: {
                keyword: string;
                /** @description 响应中经纬度的坐标系。小程序传 gcj02 */
                coord?: components["schemas"]["Coord"];
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_GeoSearchResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reverse_v1_geo_reverse_get: {
        parameters: {
            query: {
                latitude: number;
                longitude: number;
                /** @description 响应中经纬度的坐标系。小程序传 gcj02 */
                coord?: components["schemas"]["Coord"];
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_GeoReverseResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_layer_v1_map_layers__layer__get: {
        parameters: {
            query: {
                /** @description west,south,east,north */
                bbox: string;
                zoom?: number;
                /** @description 响应中经纬度的坐标系。小程序传 gcj02 */
                coord?: components["schemas"]["Coord"];
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                layer: components["schemas"]["LayerType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_LayerResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    satellite_cloud_v1_satellite_cloud_get: {
        parameters: {
            query?: {
                station_id?: string | null;
                /** @description 响应中经纬度的坐标系。小程序传 gcj02 */
                coord?: components["schemas"]["Coord"];
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SatelliteCloudResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
