"""reports

Revision ID: 01bdb634aee0
Revises: 2a5e6139f45f
Create Date: 2026-09-08 13:29:45.447931
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '01bdb634aee0'
down_revision: str | None = '2a5e6139f45f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=12), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('prompt_input', sa.String(length=4000), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'day', name='uq_report_station_day')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_station_id'), ['station_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_station_id'))

    op.drop_table('reports')
    # ### end Alembic commands ###
