"""generation_current_kw

Revision ID: 13bfd35daa54
Revises: 351d722b852f
Create Date: 2026-09-08 13:15:44.214254
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '13bfd35daa54'
down_revision: str | None = '351d722b852f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_generation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_kw', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_generation', schema=None) as batch_op:
        batch_op.drop_column('current_kw')

    # ### end Alembic commands ###
