"""alerts

Revision ID: 2a5e6139f45f
Revises: 13bfd35daa54
Create Date: 2026-09-08 13:18:59.348071
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '2a5e6139f45f'
down_revision: str | None = '13bfd35daa54'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('station_id', sa.String(length=12), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_station_id'), ['station_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_station_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_published_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_active'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
