"""daily_generation

Revision ID: 351d722b852f
Revises: d9d18a28b6ef
Create Date: 2026-09-08 12:59:41.498427
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '351d722b852f'
down_revision: str | None = 'd9d18a28b6ef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_generation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=12), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('kwh', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'day', name='uq_generation_station_day')
    )
    with op.batch_alter_table('daily_generation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_generation_station_id'), ['station_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_generation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_generation_station_id'))

    op.drop_table('daily_generation')
    # ### end Alembic commands ###
