"""catalog_plants

Revision ID: 37c98398bf8c
Revises: 01bdb634aee0
Create Date: 2026-09-08 17:53:34.725436
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '37c98398bf8c'
down_revision: str | None = '01bdb634aee0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_plants',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('name_local', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('capacity_kw', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('province', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('district', sa.String(length=32), nullable=True),
    sa.Column('owner_name', sa.String(length=128), nullable=True),
    sa.Column('commissioning_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog_plants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_plants_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_plants_longitude'), ['longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_plants_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_plants_type'), ['type'], unique=False)

    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalog_id', sa.String(length=24), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_column('catalog_id')

    with op.batch_alter_table('catalog_plants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_plants_type'))
        batch_op.drop_index(batch_op.f('ix_catalog_plants_source'))
        batch_op.drop_index(batch_op.f('ix_catalog_plants_longitude'))
        batch_op.drop_index(batch_op.f('ix_catalog_plants_latitude'))

    op.drop_table('catalog_plants')
    # ### end Alembic commands ###
