"""stations

Revision ID: d9d18a28b6ef
Revises: 
Create Date: 2026-09-08 11:54:28.972025
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'd9d18a28b6ef'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('capacity_kw', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('tilt', sa.Float(), nullable=True),
    sa.Column('azimuth', sa.Float(), nullable=True),
    sa.Column('hub_height', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stations_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stations_owner_id'))

    op.drop_table('stations')
    # ### end Alembic commands ###
